services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn sleep_stakes.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  ui:
    build: ./ui
    container_name: frontend
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume:
  media_volume: