# Generated by Django 4.2.3 on 2025-05-13 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_hangout_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangout',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
